### PR TITLE
stricter typing for enums

### PR DESCRIPTION
**Pull request by John-Colvin**
I think the global symbols should have the same type as the ones in the aggregate.

### CODE REVIEW

**Comment by atilaneves** [comment]
With no tests to accompany the patch, I'm not sure what it does.

In any case I think I've finally made up my mind about how to deal with enums. The global symbols seemed like a good idea until I tried using them and the C functions that take or return enums wouldn't type-check in D. I considered translating those as ints, but that's its own problem. So I think the way forward is to not have global symbols anymore and enable them with a command-line option that also translates enums as function parameters or return types as int.

**Comment by John-Colvin** [comment]
I don't follow what you mean by "C functions that take or return enums wouldn't type-check in D".

Is it possible that this patch helps by typing the bare enums ("globals" as you called them) the same as the member ones?

**Comment by atilaneves** [comment]
What I meant was if the C header looks like this:

```c
enum Enum { one, two, three };
Enum fun(int, int);
void gun(Enum);
```

Then their example code probably looks like this:

```c
Enum e = fun(42, 33);
gun(two);
```
Having used the C bindings for libclang that dstep did before the enums were simplified there, it was a pain to work with enums like `CXCursorKind.CXCursor_UnexposedDecl`. So I decided that the best way to go forward was to have a bare enum called `CXCursor_UnexposedDecl` but also the "natural" translation of  having a normal named enum in D so one can, e.g., use `EnumMembers` on it.

However, going back to my example at the top, currently it gets translated as:

```d
enum Enum { one, two, three }
enum { one, two, three }
extern(C) Enum fun(int, int);
extern(C) void gun(Enum);
```
The idea was to be able to use either `one` or `Enum.one`, and even to reflect on `Enum`. But (from the example code):

```d
gun(two);
```

```
Error: function bar.gun(Enum) is not callable using argument types (int)
```

Oops. Ok, so we change the translations of the functions to accomodate using bare enums then:

```d
enum Enum { one, two, three }
enum { one, two, three }
extern(C) int fun(int, int);
extern(C) void gun(int);
```
Well, the user now looks at the C header and sees `Enum fun(int, int);`, and/or they read the example code in C so they write:

```d
Enum e = fun(42, 33);
```

```
Error: cannot implicitly convert expression fun(42, 33) of type int to Enum
```

Oops.

**Comment by John-Colvin** [comment]
I have added that example as a test to show it works now.

**Comment by atilaneves** [comment]
Amazing - your solution is so simple I have no idea how I didn't see it!

**Comment by John-Colvin** [comment]
I spent a lot of painful time porting the openCL headers, learned a few lessons there.

**Pull request merged**
